import type {EntityType, Transfer} from "@/data/types";
import type {VisualizationIntent} from "./intents";

export type RankedAddress = {address: string; type: EntityType; sent: number; received: number; transferCount: number; uniqueCounterparties: number};
export type RankedFlow = {id: string; txHash: Transfer["txHash"]; from: Transfer["from"]; to: Transfer["to"]; amount: number; blockNumber: string; timestamp?: number};
export type ActivityCategory = `${EntityType}-to-${EntityType}`;
export type ActivitySlice = {category: ActivityCategory; count: number; volume: number; transferPercent: number; volumePercent: number};
export type EntityIntelligence = RankedAddress & {
  netFlow: number;
  observedVolume: number;
  observedVolumeShare: number;
  activityRank: number | null;
  volumeRank: number | null;
  largestSent: RankedFlow | null;
  largestReceived: RankedFlow | null;
  largestRelated: RankedFlow | null;
  relatedTransferIds: string[];
  whyItMatters: string;
};
export type SignalEvidence = {label: string; value: number; unit: "USDC" | "percent" | "count"};
export type AerisSignal = {
  id: string;
  type: "large-flow" | "flow-concentration" | "repeated-counterparty" | "receiver-concentration" | "sender-concentration" | "contract-activity" | "high-counterparty-activity" | "contract-flow" | "activity-mix" | "new-contract-activity";
  severity: "information" | "notable";
  importance: number;
  title: string;
  description: string;
  relatedAddresses: string[];
  relatedTransferIds: string[];
  evidence: SignalEvidence[];
  intent: VisualizationIntent;
  metric: SignalEvidence;
};
export type IntelligenceSnapshot = {
  generatedAt: number;
  transferCount: number;
  totalVolume: number;
  uniqueAddresses: number;
  activeContracts: number;
  largestTransfer: RankedFlow | null;
  topFlows: RankedFlow[];
  topSenders: EntityIntelligence[];
  topReceivers: EntityIntelligence[];
  topContracts: EntityIntelligence[];
  mostActiveByCount: EntityIntelligence[];
  mostActiveByVolume: EntityIntelligence[];
  entities: EntityIntelligence[];
  concentration: {largestTransferPercent: number; topThreePercent: number; topReceiverPercent: number; topSenderPercent: number; contractInteractionPercent: number};
  activityBreakdown: ActivitySlice[];
  networkActivity: {observedEvents: number; observedTransactions: number; contractInteractions: number; contractDeployments: number; activeContracts: number; uniqueInteractingAddresses: number; topContractInteractionCount: number; interactionConcentrationPercent: number};
  signals: AerisSignal[];
};
